
package uk.ac.ebi.webservices.ebeye;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "EBISearchService", targetNamespace = "http://www.ebi.ac.uk/EBISearchService")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EBISearchService {


    /**
     * 
     * @param domain
     * @return
     *     returns uk.ac.ebi.webservices.ebeye.ArrayOfString
     */
    @WebMethod(action = "urn:GetDomainsReferencedInDomain")
    @WebResult(name = "arrayOfDomainNames", targetNamespace = "http://www.ebi.ac.uk/EBISearchService")
    @RequestWrapper(localName = "getDomainsReferencedInDomain", targetNamespace = "http://www.ebi.ac.uk/EBISearchService", className = "uk.ac.ebi.webservices.ebeye.GetDomainsReferencedInDomain")
    @ResponseWrapper(localName = "getDomainsReferencedInDomainResponse", targetNamespace = "http://www.ebi.ac.uk/EBISearchService", className = "uk.ac.ebi.webservices.ebeye.GetDomainsReferencedInDomainResponse")
    public ArrayOfString getDomainsReferencedInDomain(
        @WebParam(name = "domain", targetNamespace = "http://www.ebi.ac.uk/EBISearchService")
        String domain);

    /**
     * 
     * @param domain
     * @param entries
     * @param fields
     * @return
     *     returns uk.ac.ebi.webservices.ebeye.ArrayOfArrayOfString
     */
    @WebMethod(action = "urn:GetEntries")
    @WebResult(name = "arrayOfEntryValues", targetNamespace = "http://www.ebi.ac.uk/EBISearchService")
    @RequestWrapper(localName = "getEntries", targetNamespace = "http://www.ebi.ac.uk/EBISearchService", className = "uk.ac.ebi.webservices.ebeye.GetEntries")
    @ResponseWrapper(localName = "getEntriesResponse", targetNamespace = "http://www.ebi.ac.uk/EBISearchService", className = "uk.ac.ebi.webservices.ebeye.GetEntriesResponse")
    public ArrayOfArrayOfString getEntries(
        @WebParam(name = "domain", targetNamespace = "http://www.ebi.ac.uk/EBISearchService")
        String domain,
        @WebParam(name = "entries", targetNamespace = "http://www.ebi.ac.uk/EBISearchService")
        ArrayOfString entries,
        @WebParam(name = "fields", targetNamespace = "http://www.ebi.ac.uk/EBISearchService")
        ArrayOfString fields);

    /**
     * 
     * @param entry
     * @param domain
     * @param fields
     * @return
     *     returns uk.ac.ebi.webservices.ebeye.ArrayOfString
     */
    @WebMethod(action = "urn:GetEntryFieldUrls")
    @WebResult(name = "entryUrlsValues", targetNamespace = "http://www.ebi.ac.uk/EBISearchService")
    @RequestWrapper(localName = "getEntryFieldUrls", targetNamespace = "http://www.ebi.ac.uk/EBISearchService", className = "uk.ac.ebi.webservices.ebeye.GetEntryFieldUrls")
    @ResponseWrapper(localName = "getEntryFieldUrlsResponse", targetNamespace = "http://www.ebi.ac.uk/EBISearchService", className = "uk.ac.ebi.webservices.ebeye.GetEntryFieldUrlsResponse")
    public ArrayOfString getEntryFieldUrls(
        @WebParam(name = "domain", targetNamespace = "http://www.ebi.ac.uk/EBISearchService")
        String domain,
        @WebParam(name = "entry", targetNamespace = "http://www.ebi.ac.uk/EBISearchService")
        String entry,
        @WebParam(name = "fields", targetNamespace = "http://www.ebi.ac.uk/EBISearchService")
        ArrayOfString fields);

    /**
     * 
     * @param domain
     * @return
     *     returns uk.ac.ebi.webservices.ebeye.ArrayOfString
     */
    @WebMethod(action = "urn:ListFields")
    @WebResult(name = "arrayOfFieldNames", targetNamespace = "http://www.ebi.ac.uk/EBISearchService")
    @RequestWrapper(localName = "listFields", targetNamespace = "http://www.ebi.ac.uk/EBISearchService", className = "uk.ac.ebi.webservices.ebeye.ListFields")
    @ResponseWrapper(localName = "listFieldsResponse", targetNamespace = "http://www.ebi.ac.uk/EBISearchService", className = "uk.ac.ebi.webservices.ebeye.ListFieldsResponse")
    public ArrayOfString listFields(
        @WebParam(name = "domain", targetNamespace = "http://www.ebi.ac.uk/EBISearchService")
        String domain);

    /**
     * 
     * @param query
     * @param flat
     * @param domain
     * @return
     *     returns uk.ac.ebi.webservices.ebeye.DomainResult
     */
    @WebMethod(action = "urn:GetDetailledNumberOfResults")
    @WebResult(name = "detailledNumberOfResults", targetNamespace = "http://www.ebi.ac.uk/EBISearchService")
    @RequestWrapper(localName = "getDetailledNumberOfResults", targetNamespace = "http://www.ebi.ac.uk/EBISearchService", className = "uk.ac.ebi.webservices.ebeye.GetDetailledNumberOfResults")
    @ResponseWrapper(localName = "getDetailledNumberOfResultsResponse", targetNamespace = "http://www.ebi.ac.uk/EBISearchService", className = "uk.ac.ebi.webservices.ebeye.GetDetailledNumberOfResultsResponse")
    public DomainResult getDetailledNumberOfResults(
        @WebParam(name = "domain", targetNamespace = "http://www.ebi.ac.uk/EBISearchService")
        String domain,
        @WebParam(name = "query", targetNamespace = "http://www.ebi.ac.uk/EBISearchService")
        String query,
        @WebParam(name = "flat", targetNamespace = "http://www.ebi.ac.uk/EBISearchService")
        boolean flat);

    /**
     * 
     * @param domain
     * @return
     *     returns uk.ac.ebi.webservices.ebeye.ArrayOfFieldInfo
     */
    @WebMethod(action = "urn:ListFieldsInformation")
    @WebResult(name = "arrayOfFieldInformation", targetNamespace = "http://www.ebi.ac.uk/EBISearchService")
    @RequestWrapper(localName = "listFieldsInformation", targetNamespace = "http://www.ebi.ac.uk/EBISearchService", className = "uk.ac.ebi.webservices.ebeye.ListFieldsInformation")
    @ResponseWrapper(localName = "listFieldsInformationResponse", targetNamespace = "http://www.ebi.ac.uk/EBISearchService", className = "uk.ac.ebi.webservices.ebeye.ListFieldsInformationResponse")
    public ArrayOfFieldInfo listFieldsInformation(
        @WebParam(name = "domain", targetNamespace = "http://www.ebi.ac.uk/EBISearchService")
        String domain);

    /**
     * 
     * @param entry
     * @param domain
     * @param fields
     * @return
     *     returns uk.ac.ebi.webservices.ebeye.ArrayOfString
     */
    @WebMethod(action = "urn:GetEntry")
    @WebResult(name = "entryValues", targetNamespace = "http://www.ebi.ac.uk/EBISearchService")
    @RequestWrapper(localName = "getEntry", targetNamespace = "http://www.ebi.ac.uk/EBISearchService", className = "uk.ac.ebi.webservices.ebeye.GetEntry")
    @ResponseWrapper(localName = "getEntryResponse", targetNamespace = "http://www.ebi.ac.uk/EBISearchService", className = "uk.ac.ebi.webservices.ebeye.GetEntryResponse")
    public ArrayOfString getEntry(
        @WebParam(name = "domain", targetNamespace = "http://www.ebi.ac.uk/EBISearchService")
        String domain,
        @WebParam(name = "entry", targetNamespace = "http://www.ebi.ac.uk/EBISearchService")
        String entry,
        @WebParam(name = "fields", targetNamespace = "http://www.ebi.ac.uk/EBISearchService")
        ArrayOfString fields);

    /**
     * 
     * @param query
     * @param domain
     * @return
     *     returns int
     */
    @WebMethod(action = "urn:GetNumberOfResults")
    @WebResult(name = "numberOfResults", targetNamespace = "http://www.ebi.ac.uk/EBISearchService")
    @RequestWrapper(localName = "getNumberOfResults", targetNamespace = "http://www.ebi.ac.uk/EBISearchService", className = "uk.ac.ebi.webservices.ebeye.GetNumberOfResults")
    @ResponseWrapper(localName = "getNumberOfResultsResponse", targetNamespace = "http://www.ebi.ac.uk/EBISearchService", className = "uk.ac.ebi.webservices.ebeye.GetNumberOfResultsResponse")
    public int getNumberOfResults(
        @WebParam(name = "domain", targetNamespace = "http://www.ebi.ac.uk/EBISearchService")
        String domain,
        @WebParam(name = "query", targetNamespace = "http://www.ebi.ac.uk/EBISearchService")
        String query);

    /**
     * 
     * @param referencedDomain
     * @param entry
     * @param domain
     * @return
     *     returns uk.ac.ebi.webservices.ebeye.ArrayOfString
     */
    @WebMethod(action = "urn:GetReferencedEntries")
    @WebResult(name = "arrayOfEntryIds", targetNamespace = "http://www.ebi.ac.uk/EBISearchService")
    @RequestWrapper(localName = "getReferencedEntries", targetNamespace = "http://www.ebi.ac.uk/EBISearchService", className = "uk.ac.ebi.webservices.ebeye.GetReferencedEntries")
    @ResponseWrapper(localName = "getReferencedEntriesResponse", targetNamespace = "http://www.ebi.ac.uk/EBISearchService", className = "uk.ac.ebi.webservices.ebeye.GetReferencedEntriesResponse")
    public ArrayOfString getReferencedEntries(
        @WebParam(name = "domain", targetNamespace = "http://www.ebi.ac.uk/EBISearchService")
        String domain,
        @WebParam(name = "entry", targetNamespace = "http://www.ebi.ac.uk/EBISearchService")
        String entry,
        @WebParam(name = "referencedDomain", targetNamespace = "http://www.ebi.ac.uk/EBISearchService")
        String referencedDomain);

    /**
     * 
     * @param domain
     * @return
     *     returns uk.ac.ebi.webservices.ebeye.ArrayOfString
     */
    @WebMethod(action = "urn:ListAdditionalReferenceFields")
    @WebResult(name = "arrayOfFieldNames", targetNamespace = "http://www.ebi.ac.uk/EBISearchService")
    @RequestWrapper(localName = "listAdditionalReferenceFields", targetNamespace = "http://www.ebi.ac.uk/EBISearchService", className = "uk.ac.ebi.webservices.ebeye.ListAdditionalReferenceFields")
    @ResponseWrapper(localName = "listAdditionalReferenceFieldsResponse", targetNamespace = "http://www.ebi.ac.uk/EBISearchService", className = "uk.ac.ebi.webservices.ebeye.ListAdditionalReferenceFieldsResponse")
    public ArrayOfString listAdditionalReferenceFields(
        @WebParam(name = "domain", targetNamespace = "http://www.ebi.ac.uk/EBISearchService")
        String domain);

    /**
     * 
     * @param domain
     * @param entries
     * @param fields
     * @return
     *     returns uk.ac.ebi.webservices.ebeye.ArrayOfArrayOfString
     */
    @WebMethod(action = "urn:GetEntriesFieldUrls")
    @WebResult(name = "arrayOfEntryUrlsValues", targetNamespace = "http://www.ebi.ac.uk/EBISearchService")
    @RequestWrapper(localName = "getEntriesFieldUrls", targetNamespace = "http://www.ebi.ac.uk/EBISearchService", className = "uk.ac.ebi.webservices.ebeye.GetEntriesFieldUrls")
    @ResponseWrapper(localName = "getEntriesFieldUrlsResponse", targetNamespace = "http://www.ebi.ac.uk/EBISearchService", className = "uk.ac.ebi.webservices.ebeye.GetEntriesFieldUrlsResponse")
    public ArrayOfArrayOfString getEntriesFieldUrls(
        @WebParam(name = "domain", targetNamespace = "http://www.ebi.ac.uk/EBISearchService")
        String domain,
        @WebParam(name = "entries", targetNamespace = "http://www.ebi.ac.uk/EBISearchService")
        ArrayOfString entries,
        @WebParam(name = "fields", targetNamespace = "http://www.ebi.ac.uk/EBISearchService")
        ArrayOfString fields);

    /**
     * 
     * @param entry
     * @param domain
     * @return
     *     returns uk.ac.ebi.webservices.ebeye.ArrayOfString
     */
    @WebMethod(action = "urn:GetDomainsReferencedInEntry")
    @WebResult(name = "arrayOfDomainNames", targetNamespace = "http://www.ebi.ac.uk/EBISearchService")
    @RequestWrapper(localName = "getDomainsReferencedInEntry", targetNamespace = "http://www.ebi.ac.uk/EBISearchService", className = "uk.ac.ebi.webservices.ebeye.GetDomainsReferencedInEntry")
    @ResponseWrapper(localName = "getDomainsReferencedInEntryResponse", targetNamespace = "http://www.ebi.ac.uk/EBISearchService", className = "uk.ac.ebi.webservices.ebeye.GetDomainsReferencedInEntryResponse")
    public ArrayOfString getDomainsReferencedInEntry(
        @WebParam(name = "domain", targetNamespace = "http://www.ebi.ac.uk/EBISearchService")
        String domain,
        @WebParam(name = "entry", targetNamespace = "http://www.ebi.ac.uk/EBISearchService")
        String entry);

    /**
     * 
     * @param referencedDomain
     * @param domain
     * @param entries
     * @param fields
     * @return
     *     returns uk.ac.ebi.webservices.ebeye.ArrayOfArrayOfString
     */
    @WebMethod(action = "urn:GetReferencedEntriesFlatSet")
    @WebResult(name = "arrayOfEntryValues", targetNamespace = "http://www.ebi.ac.uk/EBISearchService")
    @RequestWrapper(localName = "getReferencedEntriesFlatSet", targetNamespace = "http://www.ebi.ac.uk/EBISearchService", className = "uk.ac.ebi.webservices.ebeye.GetReferencedEntriesFlatSet")
    @ResponseWrapper(localName = "getReferencedEntriesFlatSetResponse", targetNamespace = "http://www.ebi.ac.uk/EBISearchService", className = "uk.ac.ebi.webservices.ebeye.GetReferencedEntriesFlatSetResponse")
    public ArrayOfArrayOfString getReferencedEntriesFlatSet(
        @WebParam(name = "domain", targetNamespace = "http://www.ebi.ac.uk/EBISearchService")
        String domain,
        @WebParam(name = "entries", targetNamespace = "http://www.ebi.ac.uk/EBISearchService")
        ArrayOfString entries,
        @WebParam(name = "referencedDomain", targetNamespace = "http://www.ebi.ac.uk/EBISearchService")
        String referencedDomain,
        @WebParam(name = "fields", targetNamespace = "http://www.ebi.ac.uk/EBISearchService")
        ArrayOfString fields);

    /**
     * 
     * @param start
     * @param query
     * @param domain
     * @param size
     * @return
     *     returns uk.ac.ebi.webservices.ebeye.ArrayOfString
     */
    @WebMethod(action = "urn:GetResultsIds")
    @WebResult(name = "arrayOfIds", targetNamespace = "http://www.ebi.ac.uk/EBISearchService")
    @RequestWrapper(localName = "getResultsIds", targetNamespace = "http://www.ebi.ac.uk/EBISearchService", className = "uk.ac.ebi.webservices.ebeye.GetResultsIds")
    @ResponseWrapper(localName = "getResultsIdsResponse", targetNamespace = "http://www.ebi.ac.uk/EBISearchService", className = "uk.ac.ebi.webservices.ebeye.GetResultsIdsResponse")
    public ArrayOfString getResultsIds(
        @WebParam(name = "domain", targetNamespace = "http://www.ebi.ac.uk/EBISearchService")
        String domain,
        @WebParam(name = "query", targetNamespace = "http://www.ebi.ac.uk/EBISearchService")
        String query,
        @WebParam(name = "start", targetNamespace = "http://www.ebi.ac.uk/EBISearchService")
        int start,
        @WebParam(name = "size", targetNamespace = "http://www.ebi.ac.uk/EBISearchService")
        int size);

    /**
     * 
     * @param referencedDomain
     * @param domain
     * @param entries
     * @param fields
     * @return
     *     returns uk.ac.ebi.webservices.ebeye.ArrayOfEntryReferences
     */
    @WebMethod(action = "urn:GetReferencedEntriesSet")
    @WebResult(name = "arrayOfEntryValues", targetNamespace = "http://www.ebi.ac.uk/EBISearchService")
    @RequestWrapper(localName = "getReferencedEntriesSet", targetNamespace = "http://www.ebi.ac.uk/EBISearchService", className = "uk.ac.ebi.webservices.ebeye.GetReferencedEntriesSet")
    @ResponseWrapper(localName = "getReferencedEntriesSetResponse", targetNamespace = "http://www.ebi.ac.uk/EBISearchService", className = "uk.ac.ebi.webservices.ebeye.GetReferencedEntriesSetResponse")
    public ArrayOfEntryReferences getReferencedEntriesSet(
        @WebParam(name = "domain", targetNamespace = "http://www.ebi.ac.uk/EBISearchService")
        String domain,
        @WebParam(name = "entries", targetNamespace = "http://www.ebi.ac.uk/EBISearchService")
        ArrayOfString entries,
        @WebParam(name = "referencedDomain", targetNamespace = "http://www.ebi.ac.uk/EBISearchService")
        String referencedDomain,
        @WebParam(name = "fields", targetNamespace = "http://www.ebi.ac.uk/EBISearchService")
        ArrayOfString fields);

    /**
     * 
     * @return
     *     returns uk.ac.ebi.webservices.ebeye.ArrayOfString
     */
    @WebMethod(action = "urn:ListDomains")
    @WebResult(name = "arrayOfDomainNames", targetNamespace = "http://www.ebi.ac.uk/EBISearchService")
    @RequestWrapper(localName = "listDomains", targetNamespace = "http://www.ebi.ac.uk/EBISearchService", className = "uk.ac.ebi.webservices.ebeye.ListDomains")
    @ResponseWrapper(localName = "listDomainsResponse", targetNamespace = "http://www.ebi.ac.uk/EBISearchService", className = "uk.ac.ebi.webservices.ebeye.ListDomainsResponse")
    public ArrayOfString listDomains();

    /**
     * 
     * @return
     *     returns uk.ac.ebi.webservices.ebeye.DomainDescription
     */
    @WebMethod(action = "urn:GetDomainsHierarchy")
    @WebResult(name = "rootDomain", targetNamespace = "http://www.ebi.ac.uk/EBISearchService")
    @RequestWrapper(localName = "getDomainsHierarchy", targetNamespace = "http://www.ebi.ac.uk/EBISearchService", className = "uk.ac.ebi.webservices.ebeye.GetDomainsHierarchy")
    @ResponseWrapper(localName = "getDomainsHierarchyResponse", targetNamespace = "http://www.ebi.ac.uk/EBISearchService", className = "uk.ac.ebi.webservices.ebeye.GetDomainsHierarchyResponse")
    public DomainDescription getDomainsHierarchy();

    /**
     * 
     * @param query
     * @param domain
     * @return
     *     returns uk.ac.ebi.webservices.ebeye.ArrayOfString
     */
    @WebMethod(action = "urn:GetAllResultsIds")
    @WebResult(name = "arrayOfIds", targetNamespace = "http://www.ebi.ac.uk/EBISearchService")
    @RequestWrapper(localName = "getAllResultsIds", targetNamespace = "http://www.ebi.ac.uk/EBISearchService", className = "uk.ac.ebi.webservices.ebeye.GetAllResultsIds")
    @ResponseWrapper(localName = "getAllResultsIdsResponse", targetNamespace = "http://www.ebi.ac.uk/EBISearchService", className = "uk.ac.ebi.webservices.ebeye.GetAllResultsIdsResponse")
    public ArrayOfString getAllResultsIds(
        @WebParam(name = "domain", targetNamespace = "http://www.ebi.ac.uk/EBISearchService")
        String domain,
        @WebParam(name = "query", targetNamespace = "http://www.ebi.ac.uk/EBISearchService")
        String query);

    /**
     * 
     * @param start
     * @param query
     * @param domain
     * @param size
     * @param fields
     * @return
     *     returns uk.ac.ebi.webservices.ebeye.ArrayOfArrayOfString
     */
    @WebMethod(action = "urn:GetResults")
    @WebResult(name = "arrayOfEntryValues", targetNamespace = "http://www.ebi.ac.uk/EBISearchService")
    @RequestWrapper(localName = "getResults", targetNamespace = "http://www.ebi.ac.uk/EBISearchService", className = "uk.ac.ebi.webservices.ebeye.GetResults")
    @ResponseWrapper(localName = "getResultsResponse", targetNamespace = "http://www.ebi.ac.uk/EBISearchService", className = "uk.ac.ebi.webservices.ebeye.GetResultsResponse")
    public ArrayOfArrayOfString getResults(
        @WebParam(name = "domain", targetNamespace = "http://www.ebi.ac.uk/EBISearchService")
        String domain,
        @WebParam(name = "query", targetNamespace = "http://www.ebi.ac.uk/EBISearchService")
        String query,
        @WebParam(name = "fields", targetNamespace = "http://www.ebi.ac.uk/EBISearchService")
        ArrayOfString fields,
        @WebParam(name = "start", targetNamespace = "http://www.ebi.ac.uk/EBISearchService")
        int start,
        @WebParam(name = "size", targetNamespace = "http://www.ebi.ac.uk/EBISearchService")
        int size);

}
