
package uk.ac.ebi.webservices.ebeye;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "EBISearchService", targetNamespace = "http://www.ebi.ac.uk/EBISearchService", wsdlLocation = "http://www.ebi.ac.uk/ebisearch/service.ebi?wsdl")
public class EBISearchService_Service
    extends Service
{

    private final static URL EBISEARCHSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(uk.ac.ebi.webservices.ebeye.EBISearchService_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = uk.ac.ebi.webservices.ebeye.EBISearchService_Service.class.getResource(".");
            url = new URL(baseUrl, "http://www.ebi.ac.uk/ebisearch/service.ebi?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://www.ebi.ac.uk/ebisearch/service.ebi?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        EBISEARCHSERVICE_WSDL_LOCATION = url;
    }

    public EBISearchService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EBISearchService_Service() {
        super(EBISEARCHSERVICE_WSDL_LOCATION, new QName("http://www.ebi.ac.uk/EBISearchService", "EBISearchService"));
    }

    /**
     * 
     * @return
     *     returns EBISearchService
     */
    @WebEndpoint(name = "EBISearchServiceHttpPort")
    public EBISearchService getEBISearchServiceHttpPort() {
        return super.getPort(new QName("http://www.ebi.ac.uk/EBISearchService", "EBISearchServiceHttpPort"), EBISearchService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EBISearchService
     */
    @WebEndpoint(name = "EBISearchServiceHttpPort")
    public EBISearchService getEBISearchServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.ebi.ac.uk/EBISearchService", "EBISearchServiceHttpPort"), EBISearchService.class, features);
    }

}
