//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.28 at 03:23:18 PM BST 
//


package uk.ac.ebi.ep.config.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the uk.ac.ebi.ep.config package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ResultFieldList_QNAME = new QName("http://ebi.ac.uk/enzymeportal", "ResultFieldList");
    private final static QName _Field_QNAME = new QName("http://ebi.ac.uk/enzymeportal", "Field");
    private final static QName _SearchField_QNAME = new QName("http://ebi.ac.uk/enzymeportal", "SearchField");
    private final static QName _Domain_QNAME = new QName("http://ebi.ac.uk/enzymeportal", "Domain");
    private final static QName _ResultField_QNAME = new QName("http://ebi.ac.uk/enzymeportal", "ResultField");
    private final static QName _EnzymeRelatedDomains_QNAME = new QName("http://ebi.ac.uk/enzymeportal", "EnzymeRelatedDomains");
    private final static QName _SearchFieldList_QNAME = new QName("http://ebi.ac.uk/enzymeportal", "SearchFieldList");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: uk.ac.ebi.ep.config
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EnzymeRelatedDomains }
     * 
     */
    public EnzymeRelatedDomains createEnzymeRelatedDomains() {
        return new EnzymeRelatedDomains();
    }

    /**
     * Create an instance of {@link ResultField }
     * 
     */
    public ResultField createResultField() {
        return new ResultField();
    }

    /**
     * Create an instance of {@link SearchFieldList }
     * 
     */
    public SearchFieldList createSearchFieldList() {
        return new SearchFieldList();
    }

    /**
     * Create an instance of {@link SearchField }
     * 
     */
    public SearchField createSearchField() {
        return new SearchField();
    }

    /**
     * Create an instance of {@link ResultFieldList }
     * 
     */
    public ResultFieldList createResultFieldList() {
        return new ResultFieldList();
    }

    /**
     * Create an instance of {@link Field }
     * 
     */
    public Field createField() {
        return new Field();
    }

    /**
     * Create an instance of {@link Domain }
     * 
     */
    public Domain createDomain() {
        return new Domain();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResultFieldList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ebi.ac.uk/enzymeportal", name = "ResultFieldList")
    public JAXBElement<ResultFieldList> createResultFieldList(ResultFieldList value) {
        return new JAXBElement<ResultFieldList>(_ResultFieldList_QNAME, ResultFieldList.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Field }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ebi.ac.uk/enzymeportal", name = "Field")
    public JAXBElement<Field> createField(Field value) {
        return new JAXBElement<Field>(_Field_QNAME, Field.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SearchField }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ebi.ac.uk/enzymeportal", name = "SearchField")
    public JAXBElement<SearchField> createSearchField(SearchField value) {
        return new JAXBElement<SearchField>(_SearchField_QNAME, SearchField.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Domain }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ebi.ac.uk/enzymeportal", name = "Domain")
    public JAXBElement<Domain> createDomain(Domain value) {
        return new JAXBElement<Domain>(_Domain_QNAME, Domain.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResultField }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ebi.ac.uk/enzymeportal", name = "ResultField")
    public JAXBElement<ResultField> createResultField(ResultField value) {
        return new JAXBElement<ResultField>(_ResultField_QNAME, ResultField.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EnzymeRelatedDomains }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ebi.ac.uk/enzymeportal", name = "EnzymeRelatedDomains")
    public JAXBElement<EnzymeRelatedDomains> createEnzymeRelatedDomains(EnzymeRelatedDomains value) {
        return new JAXBElement<EnzymeRelatedDomains>(_EnzymeRelatedDomains_QNAME, EnzymeRelatedDomains.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SearchFieldList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ebi.ac.uk/enzymeportal", name = "SearchFieldList")
    public JAXBElement<SearchFieldList> createSearchFieldList(SearchFieldList value) {
        return new JAXBElement<SearchFieldList>(_SearchFieldList_QNAME, SearchFieldList.class, null, value);
    }

}
