//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.28 at 03:23:18 PM BST 
//


package uk.ac.ebi.ep.config.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ResultField complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ResultField">
 *   &lt;complexContent>
 *     &lt;extension base="{http://ebi.ac.uk/enzymeportal}Field">
 *       &lt;sequence>
 *         &lt;element name="resultvalue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResultField", propOrder = {
    "resultvalue"
})
public class ResultField
    extends Field
{

    protected String resultvalue;

    /**
     * Gets the value of the resultvalue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResultvalue() {
        return resultvalue;
    }

    /**
     * Sets the value of the resultvalue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResultvalue(String value) {
        this.resultvalue = value;
    }

}
