//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.28 at 12:37:40 PM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ebi.ac.uk/enzymeportal")
package uk.ac.ebi.ep.config;
