//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.28 at 12:37:40 PM BST 
//


package uk.ac.ebi.ep.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Domain complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Domain">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SearchFieldList" type="{http://ebi.ac.uk/enzymeportal}SearchFieldList"/>
 *         &lt;element name="ResultFieldList" type="{http://ebi.ac.uk/enzymeportal}ResultFieldList"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Domain", propOrder = {
    "id",
    "name",
    "searchFieldList",
    "resultFieldList"
})
public class Domain {

    @XmlElement(required = true)
    protected String id;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(name = "SearchFieldList", required = true)
    protected SearchFieldList searchFieldList;
    @XmlElement(name = "ResultFieldList", required = true)
    protected ResultFieldList resultFieldList;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the searchFieldList property.
     * 
     * @return
     *     possible object is
     *     {@link SearchFieldList }
     *     
     */
    public SearchFieldList getSearchFieldList() {
        return searchFieldList;
    }

    /**
     * Sets the value of the searchFieldList property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchFieldList }
     *     
     */
    public void setSearchFieldList(SearchFieldList value) {
        this.searchFieldList = value;
    }

    /**
     * Gets the value of the resultFieldList property.
     * 
     * @return
     *     possible object is
     *     {@link ResultFieldList }
     *     
     */
    public ResultFieldList getResultFieldList() {
        return resultFieldList;
    }

    /**
     * Sets the value of the resultFieldList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResultFieldList }
     *     
     */
    public void setResultFieldList(ResultFieldList value) {
        this.resultFieldList = value;
    }

}
